### ISSUE TITLE
Metric naming and measurements

### ISSUE THREAD

**Issue by nzroller** [iZettle/dropwizard-metrics-influxdb#11]
I think it will be useful to name metrics differently in influxdb. Currently they're named with the fully qualified class name and I wonder if we could have something more general. This, together with a tag for `metricName` seems to be a good fit.

Example config:

```yaml
# Measurement mappings
measurements:
  health: "^com.example.*health^" 
  auth: "^com.example.*auth\.[^.]"
  resources: "^com.example.*\.resource\..*$"
  dao: "^com.example.*\.dao\..*$"
  datasources: "^io\.dropwizard\.db\.ManagedPooledDataSource\.db_name$"
```

This would mean that in influxdb queries you would write 
```sql 
SELECT * FROM resources WHERE metricName =~ /^com.example.resource.*$/
-- or
SELECT * FROM resources WHERE applicationName = 'example-app'
```

Note that this isn't entirely necessary since influxdb supports regular expressions for the measurements too so I'd like your feedback on this proprosal. And although there isn't much to be found about how we _should_ name our measurements I feel like reading through the documentation this is common practice.

@iZettle/horizons and @fredrikbackstrom
