### ISSUE TITLE
Question: What's the reason for excluding the 'usage' JVM metrics?

### ISSUE THREAD

**Issue by joelittlejohn** [iZettle/dropwizard-metrics-influxdb#59]
I was looking for the heap usage metric and couldn't find it, which led me to this:

https://github.com/iZettle/dropwizard-metrics-influxdb/blob/f4a8e4b713d487d3dce832e0c399e37bbf97f335/dropwizard-metrics-influxdb/src/main/java/com/izettle/metrics/dw/InfluxDbReporterFactory.java#L215

What's the reason for omitting those? Is it simply because they can be calculated?

**Comment by ngong** [comment]
In the beginning it is tailored for use in iZettle only, so we excluded all stuff seems less important. But you have the point, we shouldn't do like that anymore. At least we should move the exclusion into config file so that user of this lib could define what they want to exclude. 

Thank you very much for the heads up.

**Comment by ngong** [comment]
I just had a close look at the code, the exclusion config part is already been done, if you remove the exclusion from the config, it will work regardless the default value in code.

**Comment by joelittlejohn** [comment]
Thanks @ngong. I think that `heap.usage` is a really useful and important metric and it's a pain to have to calculate this one's self. Do you think it is worth removing `jvm.heap.usage` from the default exclusions?

**Comment by ngong** [comment]
Will do ;) 
But mean while, if you want to have `jvm.heap.usage` collected, you can do as following

Find the metrics config from your dropwizard config file, it might looks like 

```
protocol: http
host: localhost
port: 8086
tags: {} # global tags, e.g. environment or host
# only push the median (p50), the 99th percentile and the 1m rate
fields:
  timers: [p50, p99, m1_rate]
  meters: [m1_rate]
groupGauges: yes
# exclude some pre-calculated metrics
excludes:
  - ch.qos.logback.core.Appender.debug
  - ch.qos.logback.core.Appender.trace
  - io.dropwizard.jetty.MutableServletContextHandler.percent-4xx-15m
  - io.dropwizard.jetty.MutableServletContextHandler.percent-4xx-1m
  - io.dropwizard.jetty.MutableServletContextHandler.percent-4xx-5m
  - io.dropwizard.jetty.MutableServletContextHandler.percent-5xx-15m
  - io.dropwizard.jetty.MutableServletContextHandler.percent-5xx-1m
  - io.dropwizard.jetty.MutableServletContextHandler.percent-5xx-5m
  - jvm.attribute.name
  - jvm.attribute.vendor
  - jvm.memory.heap.usage
  - jvm.memory.non-heap.usage
  - jvm.memory.pools.Code-Cache.usage
  - jvm.memory.pools.Compressed-Class-Space.usage
  - jvm.memory.pools.Metaspace.usage
  - jvm.memory.pools.PS-Eden-Space.usage
  - jvm.memory.pools.PS-Old-Gen.usage
  - jvm.memory.pools.PS-Survivor-Space.usage
precision: 1m # only store time precision to the minute
prefix: ""
database: ""
auth: ""
measurementMappings: {}
defaultMeasurementMappings:
  health: .*\.health.*
  auth: .*\.auth.*
  dao: .*\.(jdbi|dao).*
  resources: .*\.resources?.*
  event_handlers: .*Handler.*
  datasources: io\.dropwizard\.db\.ManagedPooledDataSource.*
  clients: org\.apache\.http\.client\.HttpClient.*
  client_connections: org\.apache\.http\.conn\.HttpClientConnectionManager.*
  connections: org\.eclipse\.jetty\.server\.HttpConnectionFactory.*
  thread_pools: org\.eclipse\.jetty\.util\.thread\.QueuedThreadPool.*
  logs: ch\.qos\.logback\.core\.Appender.*
  http_server: io\.dropwizard\.jetty\.MutableServletContextHandler.*
  raw_sql: org\.skife\.jdbi\.v2\.DBI\.raw-sql
  jvm: ^jvm$
  jvm_attribute: jvm\.attribute.*?
  jvm_buffers: jvm\.buffers\..*
  jvm_classloader: jvm\.classloader.*
  jvm_gc: jvm\.gc\..*
  jvm_memory: jvm\.memory\..*
  jvm_threads: jvm\.threads.*
# defaults inherited from BaseReporterFactory
durationUnit: MILLISECONDS
rateUnit: SECONDS
# default inherited from MetricsFactory
frequency: 1m
```

edit the `excludes` part of the config file, this part will override the default exclusions in the code. Tailor it to what fits you the most ;)

If there is no `excludes` defined, then just add one
